apiVersion: v1
kind: PersistentVolume
metadata:
  name: esef-data-pv-{{ .Release.Namespace }}
  labels:
    app: fontem-api
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.44.0.6
    path: /srv/nfs/gmr
  mountOptions:
    - hard
    - nfsvers=4.1
