apiVersion: v1
kind: Secret
metadata:
  name: gmr-postgres-credentials
  namespace: gmr
  labels:
    app: postgresql
    managed-by: manual
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  POSTGRES_PASSWORD: gmr-pg-2026
