apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgar-data
  namespace: gmr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: edgar-data-pv
