apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgar-data
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: edgar-data-pv
