{{- if ne (toString .Values.apiIngress) "false" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fontem-api
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fontem-api
                port:
                  number: 80
{{- end }}
