apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: gmr-api
  labels:
    app: gmr-api
spec:
  type: NodePort
  selector:
    app: gmr-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
