apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fontem-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: fontem-api
    # Must match the Prometheus operator's serviceMonitorSelector
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: fontem-api
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
