apiVersion: v1
kind: Service
metadata:
  name: fontem-stats-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: fontem-stats-postgres
spec:
  type: ClusterIP
  selector:
    app: fontem-stats-postgres
  ports:
    - name: postgres
      port: {{ .Values.service.port | default 5432 }}
      targetPort: 5432
      protocol: TCP
